import type { ProjectAnalysis } from './types/analysis';

export const sampleAnalysis: ProjectAnalysis = {
  projectName: 'Example FastAPI Project',
  stack: 'FastAPI',
  languages: ['python'],
  frameworks: ['FastAPI'],
  summary: {
    controllers: 2,
    services: 1,
    repositories: 1,
    models: 2,
    apis: 3,
    dependencies: 3,
    packageDependencies: 2,
    smells: 0,
    highSeveritySmells: 0,
    mediumSeveritySmells: 0,
    lowSeveritySmells: 0,
  },
  nodes: [
    { id: 'UserRouter', label: 'UserRouter', type: 'router', filePath: 'app/routes/users.py', metadata: {} },
    { id: 'AuthRouter', label: 'AuthRouter', type: 'router', filePath: 'app/routes/auth.py', metadata: {} },
    { id: 'UserService', label: 'UserService', type: 'service', filePath: 'app/services/user_service.py', metadata: {} },
    { id: 'UserRepository', label: 'UserRepository', type: 'repository', filePath: 'app/repositories/user_repository.py', metadata: {} },
    { id: 'User', label: 'User', type: 'model', filePath: 'app/models/user.py', metadata: {} },
    { id: 'UserSchema', label: 'UserSchema', type: 'dto', filePath: 'app/schemas/user.py', metadata: {} },
  ],
  edges: [
    { id: 'edge-1', source: 'UserRouter', target: 'UserService', label: 'uses' },
    { id: 'edge-2', source: 'UserService', target: 'UserRepository', label: 'uses' },
    { id: 'edge-3', source: 'UserRepository', target: 'User', label: 'uses' },
  ],
  endpoints: [
    { method: 'GET', path: '/users', handler: 'list_users', filePath: 'app/routes/users.py' },
    { method: 'POST', path: '/users', handler: 'create_user', filePath: 'app/routes/users.py' },
    { method: 'POST', path: '/auth/login', handler: 'login', filePath: 'app/routes/auth.py' },
  ],
  files: [
    { path: 'app/routes/users.py', language: 'python', size: 1520, componentTypes: ['router'] },
    { path: 'app/services/user_service.py', language: 'python', size: 980, componentTypes: ['service'] },
    { path: 'app/repositories/user_repository.py', language: 'python', size: 740, componentTypes: ['repository'] },
    { path: 'app/models/user.py', language: 'python', size: 640, componentTypes: ['model'] },
  ],
  architectureSmells: [],
  architectureReport:
    'Architecture Report: Example FastAPI Project\n\nProject overview\nThis sample follows a layered backend architecture with routers, services, repositories, and models.\n\nRecommendations\n- Continue keeping request handling, business logic, and persistence responsibilities separate.',
  accessControl: {
    authDetected: true,
    rolesDetected: ['admin'],
    roleEnforcementDetected: true,
    summary: {
      publicEndpoints: 1,
      authenticatedEndpoints: 2,
      adminEndpoints: 0,
      employeeEndpoints: 0,
      unknownEndpoints: 0,
      unprotectedSensitiveEndpoints: 0,
    },
    endpoints: [
      {
        method: 'GET',
        path: '/users',
        handler: 'list_users',
        controller: 'Users',
        middleware: ['Depends/Security'],
        accessLevel: 'AUTHENTICATED',
        risk: 'LOW',
        reason: 'Authentication middleware was detected without a specific role.',
        filePath: 'app/routes/users.py',
      },
      {
        method: 'POST',
        path: '/users',
        handler: 'create_user',
        controller: 'Users',
        middleware: ['Depends/Security'],
        accessLevel: 'AUTHENTICATED',
        risk: 'LOW',
        reason: 'Authentication middleware was detected without a specific role.',
        filePath: 'app/routes/users.py',
      },
      {
        method: 'POST',
        path: '/auth/login',
        handler: 'login',
        controller: 'Auth',
        middleware: [],
        accessLevel: 'PUBLIC',
        risk: 'NONE',
        reason: "Endpoint contains public keyword 'login'.",
        filePath: 'app/routes/auth.py',
      },
    ],
  },
  dependencies: [
    { name: 'fastapi', version: '0.115.6', source: 'requirements.txt', ecosystem: 'python' },
    { name: 'uvicorn', version: '0.34.0', source: 'requirements.txt', ecosystem: 'python' },
  ],
};
